gpu_variant:
  - cpu
  - metal                    # [(osx and arm64)]
  - cuda-12                  # [win or (linux and x86_64)]
# Linux aarch64 needs gcc 15.2.0 due to a bug with 14.3 with vector instructions
c_compiler_version:          # [linux and aarch64]
  - 15.2.0                   # [linux and aarch64]
cxx_compiler_version:        # [linux and aarch64]
  - 15.2.0                   # [linux and aarch64]
# Linux x86_64 needs gcc 14 due to CUDA 12.8 compatibility
c_compiler_version:          # [linux and x86_64]
  - 14                       # [linux and x86_64]
cxx_compiler_version:        # [linux and x86_64]
  - 14                       # [linux and x86_64]
cuda_compiler_version:       # [win or (linux and x86_64)]
  - 12.8                     # [win or (linux and x86_64)]
# CONDA_BUILD_SYSROOT is defined in the base cbc.yaml, but it's reflected here so we can zip the keys and
# build GPU and CPU at the same time for osx-arm64. It'll need to be manually updated here if the base cbc is changed.
# This could be done using extend_keys instead, with a change to the base cbc.yaml.
# However there's currently a conda-forge bug that prevents this: https://github.com/conda/conda-build/issues/5048
MACOSX_SDK_VERSION:          # [(osx and arm64)]
  - 13.3                     # [(osx and arm64)]
  - 14.5                     # [(osx and arm64)]
CONDA_BUILD_SYSROOT:         # [(osx and arm64)]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk  # [(osx and arm64)]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX14.5.sdk  # [(osx and arm64)]
zip_keys:                    # [(osx and arm64)]
  - gpu_variant              # [(osx and arm64)]
  - MACOSX_SDK_VERSION       # [(osx and arm64)]
  - CONDA_BUILD_SYSROOT      # [(osx and arm64)]
# megabuild is disabled as our CI runners work on each python version separately.
megabuild:
- false