{% set version = "1.0.0" %}

package:
  name: pytorch-cpu
  version: {{ version }}

source:
  # The tar source needs serious patching since it is trying to build
  # all 3rd party modules
  # url: https://github.com/pytorch/pytorch/archive/v{{ version }}.tar.gz
  # fn: pytorch-v{{ version }}.tar.gz
  # sha256: f360b7954e441bc5c4b36c49e711697a5c351de8b146c2982809385e3b3cfdcb
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: v{{ version }}
  patches:
    # Accepted and will be in 1.0.1
    # https://github.com/pytorch/pytorch/commit/4047cdc6906c6e5c5e1fb837f7f479e0af149fa7
    - mac_osx_clock_getttime.patch  # [osx]

# The build needs to set many environment variables
# This is an easy way to do it cross platform
{% set export = "export" %}  # [not win]
{% set export = "set" %}     # [win]

build:
  number: 1001
  {% if 'toolchain' in compiler('cxx') %}skip: True{% endif %}  # Only build with modern compilers.
  # Support for Windows and Python 2.7 is very experimental
  # https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/21220961#L972
  skip: true  # [win and py27]
  script:
    # Most of this script is adapted from the pytorch/pythorch-cpu
    # meta.yaml.template build.sh and bld.bat scripts
    - {{ export }} TN_BINARY_BUILD=1
    - {{ export }} PYTORCH_BINARY_BUILD=1
    - {{ export }} NO_CUDA=1
    - {{ export }} PYTORCH_BUILD_VERSION={{ PKG_VERSION }}
    - {{ export }} PYTORCH_BUILD_NUMBER={{ PKG_BUILDNUM }}
    - {{ export }} BUILD_CUSTOM_PROTOBUF=OFF
    # Use ninja as the build just won't finish on windows
    - {{ export }} CMAKE_GENERATOR=Ninja
    # I'm pretty sure I only need this flag because I don't include the
    # package that provides unix-like headers for windows.
    # I forget its name now.
    #- {{ export }} GEN_TO_SOURCE=1                          # [win]
    # Why are all warnings treated as errors???
    - export CXXFLAGS="-Wno-error=unused-result $CXXFLAGS"  # [linux]
    - export CFLAGS="-Wno-error=unused-result $CFLAGS"      # [linux]
    - "{{ PYTHON }} -m pip install . --no-deps -vv --disable-pip-version-check"
      # --disable-pip-version-check is added to reduce warnings messages when debugging the build

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - msinttypes        # [win]
  host:
    - python
    - pip
    - pyyaml
    - numpy 1.11
    - setuptools
    - cffi
    - typing  # [py <= 35]
    - ninja
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - ninja
    - cffi

test:
  imports:
    - torch
    # Maybe we should have a test for a simple Neural Network???

about:
  home: https://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "PyTorch is an optimized tensor library for deep learning using GPUs and CPUs."

extra:
  recipe-maintainers:
    - hmaarrfk
    - sodre
