{% set version = "1.6.0" %}
{% set commit = "b31f58de6fa8bbda5353b3c77d9be4914399724d" %}

package:
  name: pytorch-recipe
  version: {{ version }}

source:
  # for local testing use a tarball including submodules
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: {{ commit }}
  patches:
    - nccl_socket.patch
    - remove_shared_linker_flag_override.patch
    - fix_std_stdint.patch
    - fix_dispatch_apply_auto.patch
    - fix_map_anonymous.patch
    - cpp_extension.patch

build:
  number: 0

outputs:
  - name: pytorch
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
    script: build_pytorch.sh  # [not win]
    script: bld_pytorch.bat   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
        - patch     # [not win]
        - m2-patch  # [win]
        - git       # [not win]
        - m2-git    # [win]
        - libgomp   # [linux]
        - llvm-openmp    # [osx]
      host:
        - cmake
        - git       # [not win]
        - m2-git    # [win]
        # GPU requirements
        - cudnn                           # [cuda_compiler_version != "None"]
        - nccl                            # [cuda_compiler_version != "None"]
        - magma                           # [cuda_compiler_version != "None"]
        # other requirements
        - python
        - numpy
        - pip
        - setuptools
        - pyyaml
        - requests
        - future
        - six
        - cffi
        - mkl-devel {{ mkl }}
        - mkl {{ mkl }}
        - libblas * *_mkl
        - typing
        - ninja
        - libuv       # [unix]
        - pkg-config  # [unix]
      run:
        - mkl {{ mkl }}
        - libblas * *_mkl
        - llvm-openmp    # [osx]
        #- _pytorch_select ==0.1             # [cuda_compiler_version == "None"]
        #- _pytorch_select ==0.2             # [cuda_compiler_version != "None"]
        # GPU requirements without run_exports
        - {{ pin_compatible('cudnn') }}                       # [cuda_compiler_version != "None"]
        - {{ pin_compatible('magma', max_pin='x.x.x') }}      # [cuda_compiler_version != "None"]
        # other requirements
        - python
        - {{ pin_compatible('numpy') }}
        - cffi
        - ninja
        - future  # [py2k]
        - typing  # [py2k]

    test:
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - setuptools
        - hypothesis
        - pytest
        - tabulate
        - pydot
        - mock  # [linux]
      imports:
        - torch
      source_files:
        - test
      commands:
        - OMP_NUM_THREADS=4 python ./test/run_test.py || true  # [not win]
        - python ./test/run_test.py  # [win]

  - name: pytorch-cpu   # [cuda_compiler_version == "None"]
  - name: pytorch-gpu   # [cuda_compiler_version != "None"]
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
      # weigh down cpu implementation and give cuda preference
      track_features:
        - pytorch-cpu                                      # [cuda_compiler_version == "None"]
    requirements:
      run:
        - {{ pin_subpackage("pytorch", exact=True) }}
    test:
      commands:
        - echo "hello world"

about:
  home: http://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

extra:
  recipe-maintainers:
    - hmaarrfk
    - sodre
  feedstock-name: pytorch-cpu
