{% set version = "1.7.1" %}
{% set commit = "57bffc3a8e4fee0cce31e1ff1f662ccf7b16db57" %}

package:
  name: pytorch
  version: {{ version }}

source:
  # for local testing use a tarball including submodules
  git_url: https://github.com/pytorch/pytorch.git
  git_tag: {{ commit }}
  patches:
    - nccl_socket.patch
    # It is unclear that upstream will allow us to integrate the shared linker
    # path below until their Intel compiler issues are resolved.
    - remove_shared_linker_flag_override.patch
    # https://github.com/pytorch/pytorch/pull/49281
    - fix_std_stdint.patch
    - fix_dispatch_apply_auto.patch
    - fix_map_anonymous.patch
    - cpp_extension.patch
    - fix_msvc_build_issue.patch
    # - fix_c10_export_gcc.patch
    # - do_not_check_clock_realtime.patch

build:
  number: 0
  skip: True  # [not (osx or linux64)]
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [pytorch_variant == "gpu"]
  string: cpu_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}                                      # [pytorch_variant == "cpu"]
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch    # [not win]
    - m2-patch  # [win]
    - git
    - make      # [unix]
  host:
    - cmake
    - git
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*  # [pytorch_variant == "gpu"]
    - cudnn {{ cudnn }}*              # [pytorch_variant == "gpu"]
    - magma                           # [pytorch_variant == "gpu"]
    # other requirements
    - python
    - numpy-devel {{ numpy }}
    - pip
    - setuptools
    - pyyaml
    - requests
    - future
    - six
    - cffi
    - mkl-devel {{ mkl }}   # [blas_impl == "mkl"]
    - mkl {{ mkl }}         # [blas_impl == "mkl"]
    - openblas              # [blas_impl == "openblas"]
    - typing                # [py2k]
    - ninja
    # PyTorch builds its own vendored version of libuv, so no need to supply it
    #- libuv                 # [unix]
    - pkg-config  # [unix]
    - llvm-openmp  # [osx]
    - intel-openmp  # [osx]
  run:
    - mkl {{ mkl }}     # [blas_impl == "mkl"]
    - libmklml          # [blas_impl == "mkl"]
    - libopenblas       # [blas_impl == "openblas"]
    - intel-openmp   # [osx]
    - llvm-openmp    # [osx]
    - _pytorch_select ==0.1             # [pytorch_variant == "cpu"]
    - _pytorch_select ==0.2             # [pytorch_variant == "gpu"]
    # GPU requirements
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [pytorch_variant == "gpu"]
    - {{ pin_compatible('cudnn') }}                       # [pytorch_variant == "gpu"]
    # other requirements
    - python
    - cffi
    - ninja
    - future  # [py2k]
    - typing  # [py2k]
    - typing-extensions

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - hypothesis
    - pytest
    - tabulate
    - pydot
    - mock  # [linux]
    - pip
  imports:
    - torch
  source_files:
    - test
  commands:
    - OMP_NUM_THREADS=4 python ./test/run_test.py || true  # [not win]
    - python ./test/run_test.py  # [win]
    # Run pip check so as to ensure that all pytorch packages are installed
    # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/24
    - pip check

about:
  home: https://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
