build_platform: {osx_arm64: osx_64}
test_on_native_only: true
azure:
  store_build_artifacts: true
  settings_win:
    pool:
      vmImage: windows-2019
conda_forge_output_validation: true
os_version:
  linux_64: cos7
